### ISSUE TITLE
Modify field error

### ISSUE THREAD

**Issue by Arvinff** [Cherry-toto/jizhicms#97]
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.success (19.html:1350:19)
    at l (jquery.min.js:4:24584)
    at Object.fireWith [as resolveWith] (jquery.min.js:4:25405)
    at k (jquery.min.js:6:4690)
    at XMLHttpRequest.<anonymous> (jquery.min.js:6:8494)

**Comment by Cherry-toto** [comment]
看下cache/log下面什么报错。
